
name: Node.js deploy using actions

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        lfs: true

    - run: npm install
    - run: npm run build  --base-href "/react-sample3/" --if-present
    - run: npm test
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.TOKEN }}
        target_branch: deploy # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        single-commit: true
